<?php
    if (!defined('BASEDIR')) die('You cannot call this script directly !');

    $aid = isset($_GET['aid']) ? $_GET['aid'] : -1;
?>

<!-- HEADER -->
<div class="page-header">
    <?php if ($aid > -1): ?>
    <h1><?= $l10n['edit_algo'] ?></h1>
    <?php else: ?>
    <h1><?= $l10n['new_algo'] ?> <small><?= $l10n['define_algo'] ?></small></h1>
    <?php endif ?>
</div>
<!-- CONTENT -->
<div class="row">
    <!-- LEFT COLUMN -->
    <div class="col-md-6">
        <div id="editAlert" class="alert alert-danger alert-dismissible" style="display:none">
            <button id="editAlertClose" type="button" class="close">
                <span aria-hidden="true">&times;</span><span class="sr-only"><?= $l10n['close'] ?></span>
            </button>
            <strong><?= $l10n['error'] ?></strong><div id="editAlertText"></div>
        </div>
        <form class="form-horizontal" role="form" method="post" name="algorithm">
            <div class="panel-group" id="accordion-left">

                <!-- TAB - GENERAL INFORMATION -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#genPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-right"></span> <?= $l10n['general_info'] ?>
                        </h4>
                    </div>
                    <div id="genPanel" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div id="aid" style="display: none"><?= $aid ?></div>
                            <div class="form-group">
                                <label for="in-name" class="control-label col-sm-3"><?= $l10n['algo_name'] ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="in-name" placeholder="<?= $l10n['algo_name'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="in-title" class="control-label col-sm-3"><?= $l10n['description'] ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="in-title" placeholder="<?= $l10n['description'] ?>">
                                </div>
                            </div>
                            <textarea class="form-control" id="in-desc" rows="3"
                                      data-placeholder="<?= $l10n['long_description'] ?>"><?= $l10n['long_description'] ?></textarea>
                        </div>
                    </div>
                </div>

                <!-- TAB - VARIABLES -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#varPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-right"></span> <?= $l10n['variables'] ?>
                        </h4>
                    </div>
                    <div id="varPanel" class="panel-collapse collapse in">
                        <div class="panel-body" style="text-align: center;">
                            <div class="btn btn-success btn-lg" id="btnAddVar">
                                <span class="glyphicon glyphicon-plus" style="width: 100px;"></span>
                            </div>
                            <table class="table table-condensed table-bordered variables">
                                <tbody id="insertVarsHere">
                                    <tr class="dummyRow ui-droppable" style="display: none"><td colspan="2"></td></tr>
                                </tbody>
                                <tfoot>
                                    <tr id="var-prototype" class="varRow" data-vid="" style="display: none">
                                        <!-- Variable in view mode -->
                                        <td class="content view" style="display: none">
                                            <div class="col-lg-12">
                                                <code class="cell"></code>
                                            </div>
                                        </td>
                                        <td class="buttons view" style="display: none">
                                            <div class="btn-group btn-group-xs">
                                                <button type="button" class="btn btn-default btn-var-edit" value="0" title="<?= $l10n['edit_var'] ?>">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </button>
                                                <button type="button" class="btn btn-default btn-var-remove" value="0" title="<?= $l10n['remove_var'] ?>">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </div>
                                        </td>

                                        <!-- Variable in edit mode -->
                                        <td class="content edit">
                                            <div class="col-xs-4">
                                                <div class="form-group name-group">
                                                    <label class="sr-only" for="name"><?= $l10n['var_name'] ?></label>
                                                    <input class="form-control name" value="" placeholder="<?= $l10n['name'] ?>" type="text">
                                                </div>
                                            </div>
                                            <div class="col-xs-1">
                                                <div class="cell"><code>=</code></div>
                                            </div>
                                            <div class="col-xs-4">
                                                <div class="form-group init-group">
                                                    <label class="sr-only" for="init"><?= $l10n['init'] ?></label>
                                                    <select class="form-control init">
                                                        <optgroup label="Element">
                                                            <option value="elem-?"><?= $l10n['uninitialized'] ?></option>
                                                            <option value="elem-value" data-target=".value"><?= $l10n['value'] ?></option>
                                                        </optgroup>
                                                        <optgroup label="Array">
                                                            <option value="array-?" data-target=".size"><?= $l10n['uninitialized'] ?></option>
                                                            <option value="array-random" data-target=".size"><?= $l10n['random'] ?></option>
                                                            <option value="array-custom" data-target=".value"><?= $l10n['custom'] ?></option>
                                                        </optgroup>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-xs-3">
                                                <div class="form-group value-group" style="display: none">
                                                    <label class="sr-only" for="value"><?= $l10n['init_value'] ?></label>
                                                    <input class="form-control value" value="" placeholder="<?= $l10n['value'] ?>" type="text">
                                                </div>
                                                <div class="form-group size-group" style="display: none;">
                                                    <label class="sr-only" for="size"><?= $l10n['array_size'] ?></label>
                                                    <select class="form-control size">
                                                        <optgroup label="<?= $l10n['size'] ?>">
                                                            <?php for($i = ARRAY_MIN_SIZE; $i <= ARRAY_MAX_SIZE; $i++): ?>
                                                            <option><?= $i ?></option>
                                                            <?php endfor ?>
                                                        </optgroup>
                                                    </select>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="buttons edit">
                                            <div class="btn-group btn-group-xs">
                                                <button type="button" class="btn btn-default btn-var-check" value="0" title="<?= $l10n['check_var'] ?>">
                                                    <span class="glyphicon glyphicon-ok"></span>
                                                </button>
                                                <button type="button" class="btn btn-default btn-var-cancel" value="0" title="<?= $l10n['discard_changes'] ?>">
                                                    <span class="glyphicon glyphicon-remove"></span>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- TAB - STEPS -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#stepPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-down"></span> <?= $l10n['steps'] ?>
                        </h4>
                    </div>
                    <div id="stepPanel" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table id="placeAlgorithmHere" style="width: 100%">
                                <tr>
                                    <td>
                                        <!-- IF NODE BEGIN -->
                                        <table class="step if-node" data-node-type="if">
                                            <tr>
                                                <td class="step-box top left">&nbsp;</td>
                                                <td class="step-box top right bottom full-width">if</td>
                                            </tr>
                                            <tr>
                                                <td class="step-box right left">&nbsp;</td>
                                                <td class="if-condition">
                                                    <!-- COMPARE NODE BEGIN -->
                                                    <table class="step compare-node" data-node-type="compare">
                                                        <tr>
                                                            <td class="step-box top left">&nbsp;</td>
                                                            <td class="step-box top right bottom full-width">compare</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box right left">&nbsp;</td>
                                                            <td class="compare-left">
                                                                <!-- VAR NODE BEGIN -->
                                                                <table class="step var-node" data-node-type="var">
                                                                    <tr>
                                                                        <td class="step-box top left bottom">&nbsp;</td>
                                                                        <td class="step-box top right bottom full-width">
                                                                            variable:
                                                                            <select class="var-value">
                                                                                <option value="var-0">a</option>
                                                                                <option value="var-1">b</option>
                                                                            </select>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                                <!-- VAR NODE END -->
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box left">&nbsp;</td>
                                                            <td class="step-box top right bottom half-width">
                                                                operation:
                                                                <select class="compare-operation">
                                                                    <option value="lt">&lt;</option>
                                                                    <option value="le">&le;</option>
                                                                    <option value="eq">&equals;</option>
                                                                    <option value="ge">&ge;</option>
                                                                    <option value="gt">&gt;</option>
                                                                </select>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box right bottom left">&nbsp;</td>
                                                            <td class="compare-right">
                                                                <!-- CONSTANT NODE BEGIN -->
                                                                <table class="step constant-node" data-node-type="constant">
                                                                    <tr>
                                                                        <td class="step-box top left bottom">&nbsp;</td>
                                                                        <td class="step-box top right bottom full-width">
                                                                            constant: <input class="constant-value" value="12" />
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                                <!-- CONSTANT NODE END -->
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <!-- COMPARE NODE END -->
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="step-box left">&nbsp;</td>
                                                <td class="step-box top right bottom half-width">then</td>
                                            </tr>
                                            <tr>
                                                <td class="step-box right bottom left">&nbsp;</td>
                                                <td class="if-body">
                                                    <!-- ASSIGN NODE BEGIN -->
                                                    <table class="step assign-node" data-node-type="assign">
                                                        <tr>
                                                            <td class="step-box top left">&nbsp;</td>
                                                            <td class="step-box top right bottom full-width">assign</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box left right">&nbsp;</td>
                                                            <td class="assign-from">
                                                                <!-- CONSTANT NODE BEGIN -->
                                                                <table class="step constant-node" data-node-type="constant">
                                                                    <tr>
                                                                        <td class="step-box top left bottom">&nbsp;</td>
                                                                        <td class="step-box top right bottom full-width">
                                                                            constant: <input class="constant-value" value="12" />
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                                <!-- CONSTANT NODE END -->
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box left">&nbsp;</td>
                                                            <td class="step-box top right bottom full-width">&rarr;</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="step-box left right bottom">&nbsp;</td>
                                                            <td class="assign-to">
                                                                <!-- VAR NODE BEGIN -->
                                                                <table class="step var-node" data-node-type="var">
                                                                    <tr>
                                                                        <td class="step-box top left bottom">&nbsp;</td>
                                                                        <td class="step-box top right bottom full-width">
                                                                            variable:
                                                                            <select class="var-value">
                                                                                <option value="var-0">a</option>
                                                                                <option value="var-1">b</option>
                                                                            </select>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                                <!-- VAR NODE END -->
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <!-- ASSIGN NODE END -->
                                                </td>
                                            </tr>
                                        </table>
                                        <!-- IF NODE END -->
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <!-- WHILE NODE BEGIN -->
                                        <table class="step while-node" data-node-type="while">
                                            <tr>
                                                <td class="step-box top left">&nbsp;</td>
                                                <td class="step-box top right bottom full-width">while</td>
                                            </tr>
                                            <tr>
                                                <td class="step-box right bottom left">&nbsp;</td>
                                                <td></td>
                                            </tr>
                                        </table>
                                        <!-- WHILE NODE END -->
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <span id="saveSuccess" class="label label-success" style="display: none"></span>
        </form>
    </div>
</div>