<?php
    if (!defined('ACTION')) die('You cannot call this script directly !');

    $aid = isset($_GET['aid']) ? $_GET['aid'] : -1;
?>

<!-- HEADER -->
<div class="page-header">
    <?php if ($aid > -1): ?>
    <h1>Edit algorithm <small></small></h1>
    <?php else: ?>
    <h1>New algorithm <small>Define your own algorithm!</small></h1>
    <?php endif ?>
</div>
<!-- CONTENT -->
<div class="row">
    <!-- LEFT COLUMN -->
    <div class="col-md-6">
        <form class="form-horizontal" role="form" method="post" name="algorithm">
            <div class="panel-group" id="accordion-left">

                <!-- TAB - GENERAL INFORMATION -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#genPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-right"></span> General Information
                        </h4>
                    </div>
                    <div id="genPanel" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div id="aid" style="display: none"><?= $aid ?></div>
                            <div class="form-group">
                                <label for="in-name" class="control-label col-sm-3">Algorithm name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="in-name" placeholder="Algorithm name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="in-title" class="control-label col-sm-3">Description</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="in-title" placeholder="Description in a couple of words">
                                </div>
                            </div>
                            <textarea class="form-control" id="in-desc" rows="3">Long description...</textarea>
                        </div>
                    </div>
                </div>

                <!-- TAB - VARIABLES -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#varPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-down"></span> Variables
                        </h4>
                    </div>
                    <div id="varPanel" class="panel-collapse collapse in">
                        <div class="panel-body" style="text-align: center;">
                            <div id="alert-var"></div>
                            <div class="btn-group">
                                <div class="btn btn-success btn-lg" id="btnAddVar"><span class="glyphicon glyphicon-plus" style="width: 100px;"></span></div>
                            </div>
                            <table class="table table-condensed table-bordered" style="margin-top: 10px; margin-bottom: 0px;">
                                <tbody id="insertVarsHere"></tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- TAB - STEPS -->
                <div class="panel panel-default">
                    <div class="panel-heading" data-toggle="collapse" data-target="#stepPanel">
                        <h4 class="panel-title">
                            <span class="glyphicon glyphicon-chevron-right"></span> Steps
                        </h4>
                    </div>
                    <div id="stepPanel" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table table-hover table-condensed table-bordered" id="placeStepsHere" style="display: none;"></table>
                            <button class="btn btn-primary" id="btn-addStep">+ step</button>
                        </div>
                    </div>
                </div>
            </div>

            <span id="saveAlgorithm" class="btn btn-primary btn-lg">Save</span>
            <span id="saveSuccess" class="label label-success" style="display: none"></span>
            <span id="saveError" class="label label-danger" style="display: none"></span>
        </form>
    </div>
</div>