<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');

// redirect if no aid is specified
if (!$__aid) {
    header("Location:" . url(['action' => 'new']));
    die();
}

// check authentication
if (!$__uid || !$__owner) {
    header("Location:" . url(['action' => 'view', 'aid' => $__aid]));
    die();
}

// prepare algorithm meta data
$name = stripslashes($__algorithm->name);
$description = stripslashes($__algorithm->description);
$long_description = stripslashes($__algorithm->long_description);

// prepare variables and add prototype row to variables
$vars = json_decode($__algorithm->variables);
$vars['prototype'] = (object)['name' => '', 'init' => 'elem-?', 'value' => '', 'size' => 2];

// prepare tree
require_once BASEDIR . "includes/algorithm.php";
$tree = new Tree(json_decode($__algorithm->tree));

// prepare sections
require_once BASEDIR . "includes/viewHelper.php";
$sectionNum = isset($_GET['section']) ? $_GET['section'] : SECTIONS_EDIT;
$section = sections($sectionNum, 3);

// use algorithm header
require_once BASEDIR . "partials/headers/algorithmHeader.phtml";
?>
<!-- HEADER -->
<div class="page-header">
    <h1>
        <?= $l10n['edit_algo'] ?>
        <span id="saveSuccess" class="label label-success" style="display: none"></span>
    </h1>
</div>

<!-- CONTENT -->
<div class="row">
    <!-- ERROR MESSAGE -->
    <div id="editAlert" class="alert alert-danger alert-dismissible" style="display:none">
        <button id="editAlertClose" type="button" class="close">
            <span aria-hidden="true">&times;</span><span class="sr-only"><?= $l10n['close'] ?></span>
        </button>
        <strong><?= $l10n['error'] ?></strong>

        <div id="editAlertText"></div>
    </div>
    <!-- ERROR MESSAGE END -->

    <!-- LEFT COLUMN -->
    <div class="col-md-6">
        <div class="panel-group" id="accordion-left">
            <!-- TAB - GENERAL INFORMATION -->
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#infoPanel">
                    <h4 class="panel-title">
                        <span
                            class="glyphicon glyphicon-chevron-<?php if ($section[0]): ?>down<?php else: ?>right<?php endif ?>"></span>
                        <?= $l10n['general_info'] ?>
                    </h4>
                </div>
                <div id="infoPanel" class="panel-collapse collapse <?= $section[0] ? 'in' : 'closed' ?>">
                    <div class="panel-body form-horizontal">
                        <div class="form-group">
                            <label for="in-name" class="control-label col-sm-3"><?= $l10n['algo_name'] ?></label>

                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="in-name"
                                       placeholder="<?= $l10n['algo_name'] ?>" value="<?= $name ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="in-title" class="control-label col-sm-3"><?= $l10n['description'] ?></label>

                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="in-desc"
                                       placeholder="<?= $l10n['description'] ?>" value="<?= $description ?>">
                            </div>
                        </div>
                        <textarea class="form-control" id="in-long" rows="3"
                                  data-placeholder="<?= $l10n['long_description'] ?>"><?= $long_description ?></textarea>
                    </div>
                </div>
            </div>
            <!-- TAB - GENERAL INFORMATION END -->

            <!-- TAB - VARIABLES -->
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#varPanel">
                    <h4 class="panel-title">
                        <span
                            class="glyphicon glyphicon-chevron-<?php if ($section[1]): ?>down<?php else: ?>right<?php endif ?>"></span>
                        <?= $l10n['variables'] ?>
                    </h4>
                </div>
                <div id="varPanel" class="panel-collapse collapse <?= $section[1] ? 'in' : 'closed' ?>">
                    <div class="panel-body" style="text-align: center;">
                        <table class="table table-condensed table-bordered table-hover variables">
                            <tbody id="insertVarsHere">
                            <?php foreach ($vars as $vid => $var):
                                $rowVisible = ($vid === 'prototype') ? 'style="display:none"' : '';
                                $selInit = array();
                                foreach (['elem-?', 'elem-value', 'array-?', 'array-random', 'array-custom'] as $mode) {
                                    $selInit[$mode] = $var->init === $mode ? 'selected="selected"' : '';
                                }
                                $valueVisible = ($var->init === 'elem-value' || $var->init === 'array-custom') ? '' : 'style="display:none"';
                                $sizeVisible = ($var->init === 'array-?' || $var->init === 'array-random') ? '' : 'style="display:none"';
                                ?>
                                <tr id="var-<?= $vid ?>" class="varRow" data-vid="<?= $vid ?>" <?= $rowVisible ?>
                                    data-name="<?= $var->name ?>" data-init="<?= $var->init ?>"
                                    data-value="<?= $var->value ?>" data-size="<?= $var->size ?>">

                                    <!-- Variable in view mode -->
                                    <td class="view">
                                        <div class="content">
                                            <code class="cell"><?= $var->name ?> = <?= $var->value ?></code>
                                        </div>
                                        <div class="tools">
                                            <button type="button" class="btn btn-default btn-sm btn-var-count"
                                                    title="<?= $l10n['usage_count'] ?>" data-target="var-<?= $vid ?>">
                                                <span class="glyphicon glyphicon-stats">
                                                    <code class="counter">0</code>
                                                </span>
                                            </button>
                                            <div class="btn-group btn-group-sm">
                                                <button type="button" class="btn btn-default btn-var-edit"
                                                        title="<?= $l10n['edit_var'] ?>">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </button>
                                                <button type="button" class="btn btn-default btn-var-remove"
                                                        title="<?= $l10n['remove_var'] ?>">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </div>
                                        </div>
                                    </td>

                                    <!-- Variable in edit mode -->
                                    <td class="edit" style="display: none">
                                        <div class="form-group name-group">
                                            <label class="sr-only" for="name"><?= $l10n['var_name'] ?></label>
                                            <input class="form-control input-sm name" value="<?= $var->name ?>"
                                                   placeholder="<?= $l10n['name'] ?>" type="text">
                                        </div>
                                        <div class="form-group equals-group ">
                                            <label class="sr-only" for="equals"></label>
                                            <button class="form-control input-sm disabled equals">=</button>
                                        </div>
                                        <div class="form-group init-group">
                                            <label class="sr-only" for="init"><?= $l10n['init'] ?></label>
                                            <select class="form-control input-sm init">
                                                <optgroup label="Element">
                                                    <option
                                                        value="elem-?" <?= $selInit['elem-?'] ?>><?= $l10n['uninitialized'] ?></option>
                                                    <option value="elem-value" <?= $selInit['elem-value'] ?>
                                                            data-target=".value"><?= $l10n['value'] ?></option>
                                                </optgroup>
                                                <optgroup label="Array">
                                                    <option value="array-?"  <?= $selInit['array-?'] ?>
                                                            data-target=".size"><?= $l10n['uninitialized'] ?></option>
                                                    <option value="array-random"  <?= $selInit['array-random'] ?>
                                                            data-target=".size"><?= $l10n['random'] ?></option>
                                                    <option value="array-custom"  <?= $selInit['array-custom'] ?>
                                                            data-target=".value"><?= $l10n['custom'] ?></option>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group value-group" <?= $valueVisible ?>>
                                            <label class="sr-only" for="value"><?= $l10n['init_value'] ?></label>
                                            <input class="form-control input-sm value" value="<?= $var->value ?>"
                                                   placeholder="<?= $l10n['value'] ?>" type="text">
                                        </div>
                                        <div class="form-group size-group" <?= $sizeVisible ?>>
                                            <label class="sr-only" for="size"><?= $l10n['array_size'] ?></label>
                                            <select class="form-control input-sm size">
                                                <optgroup label="<?= $l10n['size'] ?>">
                                                    <?php for ($i = ARRAY_MIN_SIZE; $i <= ARRAY_MAX_SIZE; $i++): ?>
                                                        <option
                                                            <?php if ($var->size == $i): ?>selected="selected"<?php endif ?>><?= $i ?></option>
                                                    <?php endfor ?>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="tools">
                                            <div class="btn-group btn-group-sm">
                                                <button type="button" class="btn btn-default btn-var-check"
                                                        title="<?= $l10n['check_var'] ?>">
                                                    <span class="glyphicon glyphicon-ok"></span>
                                                </button>
                                                <button type="button" class="btn btn-default btn-var-cancel"
                                                        title="<?= $l10n['discard_changes'] ?>">
                                                    <span class="glyphicon glyphicon-remove"></span>
                                                </button>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                            </tbody>
                        </table>
                        <div class="btn btn-success btn-lg" id="btnAddVar">
                            <span class="glyphicon glyphicon-plus" style="width: 100px;"></span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- TAB - VARIABLES END -->
        </div>
    </div>
    <!-- LEFT COLUMN END -->

    <!-- RIGHT COLUMN -->
    <div class="col-md-6">
        <div class="panel-group" id="accordion-right">
            <!-- TAB - STEPS -->
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#stepPanel">
                    <h4 class="panel-title">
                        <span
                            class="glyphicon glyphicon-chevron-<?php if ($section[2]): ?>down<?php else: ?>right<?php endif ?>"></span>
                        <?= $l10n['algorithm'] ?>
                    </h4>
                </div>
                <div id="stepPanel" class="panel-collapse collapse <?= $section[2] ? 'in' : 'closed' ?>">
                    <div class="panel-body algorithm" style="text-align: center">
                        <ul class="insertStepsHere" class="sortable"
                            data-node-id="0"><?php $tree->printHtml(['vars' => $vars]) ?></ul>

                        <div id="node-btn-group" class="btn-group btn-group-sm" role="group"
                             aria-label="<?= $l10n['create_a_node'] ?>">
                            <button id="btn-add-arithmetic" type="button" class="btn btn-default"
                                    data-node="node_arithmetic"><?= $l10n['arithmetic_node_title'] ?>
                            </button>
                            <button id="btn-add-assign" type="button" class="btn btn-default"
                                    data-node="node_assign"><?= $l10n['assign_node_title'] ?>
                            </button>
                            <button id="btn-add-compare" type="button" class="btn btn-default"
                                    data-node="node_compare"><?= $l10n['compare_node_title'] ?>
                            </button>
                            <button id="btn-add-constant" type="button" class="btn btn-default"
                                    data-node="node_constant"><?= $l10n['constant_node_title'] ?>
                            </button>
                            <button id="btn-add-if" type="button" class="btn btn-default" data-node="node_if">
                                <?= $l10n['if_node_title'] ?>
                            </button>
                            <button id="btn-add-inc" type="button" class="btn btn-default" data-node="node_inc">
                                <?= $l10n['inc_node_title'] ?>
                            </button>
                            <button id="btn-add-var" type="button" class="btn btn-default" data-node="node_var">
                                <?= $l10n['variable_node_title'] ?>
                            </button>
                            <button id="btn-add-while" type="button" class="btn btn-default"
                                    data-node="node_while"><?= $l10n['while_node_title'] ?>
                            </button>
                        </div>

                        <ul style="display: none">
                            <?php
                            // generate prototypes
                            Node::printPrototype(Node::ARITHMETIC_NODE, ['vars' => $vars]);
                            Node::printPrototype(Node::ASSIGN_NODE, ['vars' => $vars]);
                            Node::printPrototype(Node::COMPARE_NODE, ['vars' => $vars]);
                            Node::printPrototype(Node::CONSTANT_NODE);
                            Node::printPrototype(Node::IF_NODE);
                            Node::printPrototype(Node::INC_NODE, ['vars' => $vars]);
                            Node::printPrototype(Node::VAR_NODE, ['vars' => $vars]);
                            Node::printPrototype(Node::WHILE_NODE);
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- TAB - STEPS END -->
        </div>
    </div>
    <!-- RIGHT COLUMN END -->

</div>
<!-- CONTENT END -->