<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');

// ask database for latest algorithms
require_once BASEDIR . "includes/dataModel.php";
$_model = new DataModel();
$algorithms = $_model->fetchLatestAlgorithms(NUMBER_OF_LATEST_ALGORITHMS);
$_model->close();

require_once BASEDIR . "includes/viewHelper.php";
?>
    <!-- HEADER -->
    <div class="jumbotron">
        <h1>
            <?= PROJECT_NAME ?>
            <small><?= $l10n['subtitle'] ?></small>
        </h1>
        <p><?= $l10n['welcome_msg'] ?></p>

        <p>
            <a class="btn btn-primary btn-lg" role="button"
               href="<?= url(['action' => 'new']) ?>"><?= $l10n['define_new_algo'] ?></a>
        </p>
    </div>

<?php if (sizeof($algorithms)): ?>
    <!-- CONTENT -->
    <table class="table table-striped table-hover algorithms">
        <thead>
        <tr>
            <th><?= $l10n['latest_algos'] ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($algorithms as $algorithm):
            $linkAlgorithm = url(['action' => 'view', 'aid' => $algorithm['aid']]);
            $linkUser = url(['action' => 'user', 'uid' => $algorithm['uid']]);
            ?>
            <tr>
                <td>
                    <?php if ($algorithm['age'] <= MAX_MINUTES_FOR_LABEL): ?>
                        <span class="label label-default"><?= $l10n['label_new'] ?></span>
                    <?php endif ?>
                    <span class="name"><a href="<?= $linkAlgorithm ?>"><?= $algorithm['name'] ?></a></span>
                <span class="properties">
                    (<?= sprintf($l10n['created_note'], getTimeFrame($algorithm['age']),
                        '<a href="' . $linkUser . '">' . $algorithm['username']) . '</a>' ?>)
                </span>
                    <?php if (!empty($algorithm['description'])): ?>
                        <span class="description"><?= skipDescription($algorithm['description']) ?></span>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>