<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');
global $l10n;
require_once BASEDIR . "includes/helper/viewHelper.php";

$_tabs = [
    'overview' => 'overview',
    'users' => 'users',
    'algorithms' => 'algorithms',
    'tags' => 'tags'
];
$_tab = isset($_GET['tab']) && array_key_exists($_GET['tab'], $_tabs) ? $_GET['tab'] : 'overview';
?>
    <!-- NAVIGATION MENU FOR INDEX -->
    <ul class="nav nav-tabs">
        <li role="presentation"<?php if ($_tab === 'overview'): ?> class="active"<?php endif ?>>
            <a href="<?= url(['action' => 'index', 'tab' => 'overview']) ?>">
                <?= $l10n['overview'] ?>
            </a>
        </li>
        <li role="presentation"<?php if ($_tab === 'users'): ?> class="active"<?php endif ?>>
            <a href="<?= url(['action' => 'index', 'tab' => 'users']) ?>">
                <?= $l10n['users'] ?>
            </a>
        </li>
        <li role="presentation"<?php if ($_tab === 'algorithms'): ?> class="active"<?php endif ?>>
            <a href="<?= url(['action' => 'index', 'tab' => 'algorithms']) ?>">
                <?= $l10n['algorithms'] ?>
            </a>
        </li>
        <li role="presentation"<?php if ($_tab === 'tags'): ?> class="active"<?php endif ?>>
            <a href="<?= url(['action' => 'index', 'tab' => 'tags']) ?>">
                <?= $l10n['tags'] ?>
            </a>
        </li>
    </ul>
<?php if ($_tab === "algorithms"): ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1><?= $l10n['index'] ?>
            <small><?= $l10n['algorithms'] ?></small>
        </h1>
    </div>
    <!-- CONTENT -->
    <table id="table-algorithms" class="table table-sortable">
        <?php if ($algorithms = $__model->fetchAllPublicAlgorithms()):
            $transKeys = ['created_at', 'created_note'];
            $userData = true;
            ?>
            <thead>
            <tr>
                <th><?= $l10n['algorithm'] ?></th>
                <th><?= $l10n['tags'] ?></th>
                <th><?= $l10n['owner'] ?></th>
                <th><?= $l10n['creation'] ?></th>
                <th><?= $l10n['last_edit'] ?></th>
                <th><?= $l10n['count'] ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($algorithms as $algorithm): ?>
                <?php require(BASEDIR . 'partials/partials/item_algorithm.phtml') ?>
            <?php endforeach ?>
            </tbody>
            <?php $colCount = 6;
            require(BASEDIR . 'partials/partials/table_foot.phtml') ?>
        <?php else: ?>
            <tr>
                <td><?= $l10n['no_algorithms'] ?></td>
            </tr>
        <?php endif ?>
    </table>
<?php elseif ($_tab === 'users'): ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1><?= $l10n['index'] ?>
            <small><?= $l10n['users'] ?></small>
        </h1>
    </div>
    <!-- CONTENT -->
    <table id="table-users" class="table table-sortable">
        <?php if ($users = $__model->fetchUsers(false)): ?>
            <thead>
            <tr>
                <th><?= $l10n['user'] ?></th>
                <th title="<?= $l10n['number_of_algorithms'] ?>"><?= $l10n['algorithms'] ?></th>
                <th><?= $l10n['registration'] ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
                <?php require(BASEDIR . 'partials/partials/item_user.phtml') ?>
            <?php endforeach ?>
            </tbody>
            <?php $colCount = 3;
            require(BASEDIR . 'partials/partials/table_foot.phtml') ?>
        <?php else: ?>
            <tr>
                <td><?= $l10n['no_users'] ?></td>
            </tr>
        <?php endif ?>
    </table>
<?php elseif ($_tab === 'tags' && isset($_GET['tag'])): ?>
    <?php
    $tag = $_GET['tag'];
    $algorithms = $__model->fetchAlgorithmsByTag($tag);
    ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1><?= $l10n['index'] ?>
            <small><?= $l10n['tag'] ?> <span class="badge"><?= $tag ?></span></small>
        </h1>
    </div>
    <!-- CONTENT -->
    <table class="table table-striped table-hover algorithms">
        <?php if ($algorithms):
            $transKeys = ['created_at', 'created_note'];
            $userData = true;
            foreach ($algorithms as $algorithm) {
                require(BASEDIR . 'partials/partials/item_algorithm_compact.phtml');
            }
        else: ?>
            <tr>
                <td><?= $l10n['no_algorithms'] ?></td>
            </tr>
        <?php endif ?>
    </table>
<?php elseif ($_tab === 'tags'): ?>
    <?php
    $tags = $__model->fetchTagStats(150);
    ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1><?= $l10n['index'] ?>
            <small><?= $l10n['tags'] ?></small>
        </h1>
    </div>
    <!-- CONTENT -->
    <div class="tagcloud tagcloud-background">
        <?php require(BASEDIR . 'partials/partials/tagcloud.phtml') ?>
    </div>
<?php else: ?>
    <?php
    $latestAlgorithms = $__model->fetchLatestAlgorithms(MAX_NUMBER_OF_ENTRIES);
    $lastChanges = $__model->fetchModifiedAlgorithms(MAX_NUMBER_OF_ENTRIES);
    $diligentUsers = $__model->fetchUsersWithMostAlgorithms(MAX_NUMBER_OF_ENTRIES);
    $tags = $__model->fetchTagStats(25);
    if ($__uid) {
        $my_algorithms = $__model->fetchAlgorithmsOfUser($__uid, true, MAX_NUMBER_OF_ENTRIES);
        $my_changes = $__model->fetchModifiedAlgorithmsOfUser($__uid, MAX_NUMBER_OF_ENTRIES);
    }
    ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1><?= $l10n['index'] ?>
            <small><?= $l10n['all_algos'] ?></small>
        </h1>
    </div>
    <!-- CONTENT -->
    <div class="row">
        <div class="col-md-4">
            <!-- Latest algorithms -->
            <table class="table table-striped table-hover algorithms">
                <thead>
                <tr>
                    <th><?= $l10n['latest_algos'] ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if ($latestAlgorithms):
                    $transKeys = ['created_at', 'created_note'];
                    $userData = true;
                    foreach ($latestAlgorithms as $algorithm) {
                        require(BASEDIR . 'partials/partials/item_algorithm_compact.phtml');
                    }
                else: ?>
                    <tr>
                        <td><?= $l10n['no_algorithms'] ?></td>
                    </tr>
                <?php endif ?>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <!-- Last changes -->
            <table class="table table-striped table-hover algorithms">
                <thead>
                <tr>
                    <th><?= $l10n['last_changes'] ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if ($lastChanges):
                    $transKeys = ['modified_at', 'modified_note'];
                    $userData = true;
                    foreach ($lastChanges as $algorithm) {
                        require(BASEDIR . 'partials/partials/item_algorithm_compact.phtml');
                    }
                else: ?>
                    <tr>
                        <td><?= $l10n['no_algorithms'] ?></td>
                    </tr>
                <?php endif ?>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <!-- Users with most algorithms -->
            <table class="table table-striped table-hover algorithms">
                <thead>
                <tr>
                    <th><?= $l10n['diligent_users'] ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if ($diligentUsers):
                    foreach ($diligentUsers as $user) {
                        require(BASEDIR . 'partials/partials/item_user_compact.phtml');
                    }
                else: ?>
                    <tr>
                        <td><?= $l10n['no_users'] ?></td>
                    </tr>
                <?php endif ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <?php if ($__uid): ?>
            <div class="col-md-4">
                <!-- Own algorithms -->
                <table class="table table-striped table-hover algorithms">
                    <thead>
                    <tr>
                        <th><?= $l10n['my_algos'] ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (isset($my_algorithms) && $my_algorithms):
                        $transKeys = ['created_at', 'created_note'];
                        $userData = false;
                        foreach ($my_algorithms as $algorithm) {
                            require(BASEDIR . 'partials/partials/item_algorithm_compact.phtml');
                        }
                    else: ?>
                        <tr>
                            <td><?= $l10n['no_algorithms'] ?></td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
            <div class="col-md-4">
                <!-- Last changes -->
                <table class="table table-striped table-hover algorithms">
                    <thead>
                    <tr>
                        <th><?= $l10n['my_last_changes'] ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (isset($my_changes) && $my_changes):
                        $transKeys = ['modified_at', 'modified_note'];
                        $userData = false;
                        foreach ($my_changes as $algorithm) {
                            require(BASEDIR . 'partials/partials/item_algorithm_compact.phtml');
                        }
                    else: ?>
                        <tr>
                            <td><?= $l10n['no_algorithms'] ?></td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        <?php endif ?>
        <div class="col-md-4">
            <table class="table">
                <thead>
                <tr>
                    <th><?= $l10n['tag_cloud'] ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="tagcloud">
                        <?php require(BASEDIR . 'partials/partials/tagcloud.phtml') ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php endif ?>