<?php if (!defined('ACTION')) die('You cannot call this script directly !'); ?>
<!-- HEADER -->
<div class="jumbotron">
    <h1>
        Kartulimardikas <small>Online collection of algorithms</small>
    </h1>
    <p>Welcome to an interactive platform to discuss, demonstrate and
        compare common algorithms.</p>
    <p>
        <a class="btn btn-primary btn-lg" role="button" href="new.php#">Define
            new algorithm</a>
    </p>
</div>
<div class="page-header">
    <h1>Latest algorithms</h1>
</div>

<!-- CONTENT -->
<dl class="dl-horizontal">
    <dt>
        <a href="index.php?action=view&amp;aid=2749">Selection sort</a> <span
            class="label label-default">NEW</span>
    </dt>
    <dd>Selection sort is a sorting algorithm, specifically an in-place
        comparison sort. It has O(n2) time complexity, making it inefficient
        on large lists, and generally performs worse than the similar
        insertion sort. Selection sort is noted for its simplicity, ... <a href="index.php?action=view&amp;aid=2749">read more</a></dd>
    <dt>
        <a href="index.php?action=view&amp;aid=6930">Insertion sort</a>
    </dt>
    <dd>Insertion sort is a simple sorting algorithm that builds the
        final sorted array (or list) one item at a time. It is much less
        efficient on large lists than more advanced algorithms such as
        quicksort, heapsort, or merge sort... <a href="index.php?action=view&amp;aid=6930">read more</a></dd>
    <dt>
        <a href="index.php?action=view&amp;aid=1457">Euclidean algorithm</a>
    </dt>
    <dd>The Euclidean algorithm[a], or Euclid's algorithm, is a method
        for computing the greatest common divisor (GCD) of two (usually
        positive) integers, also known as the greatest common factor (GCF)
        or highest common factor (HCF)... <a href="index.php?action=view&amp;aid=1457">read more</a></dd>
</dl>