<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');
global $l10n;
?>
<!-- HEADER -->
<div class="page-header">
    <h1><?= $l10n['new_algo'] ?>
        <small><?= $l10n['define_algo'] ?></small>
    </h1>
</div>
<!-- CONTENT -->
<div class="alert alert-warning" role="alert">
    <strong><?= $l10n['warning'] ?></strong><br/>

    <?= $l10n['message_not_signed_in'] ?>
    <ul>
        <li><?= $l10n['use_form_to_signin'] ?></li>
        <li><?= $l10n['if_no_account'] ?> &rarr; <a
                href="<?= url(['action' => 'register']) ?>"><?= $l10n['register'] ?></a></li>
    </ul>
    <br/>
    &rarr; <a href="javascript:history.back()"><?= $l10n['go_back'] ?></a>
</div>