<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');
global $l10n;

// if a user name is specified, redirect to uid
if (isset($_GET['name'])) {
    $user = $__model->fetchUserByUsername($_GET['name']);
    header("Location:" . url(['action' => 'user', 'uid' => $user->uid], false, false));
    die();
}

require_once BASEDIR . "includes/helper/viewHelper.php";
// if a user id is specified, load user by uid
if (isset($_GET['uid'])) {
    $user = $__model->fetchUser($_GET['uid']);

// if nothing is specified, but user is signed in, load current user
} elseif ($__uid) {
    $user = $__model->fetchUser($__uid);
}
?>

<?php if (isset($user)):
    $ownAccount = $__uid === $user->uid;
    $algorithms = $__model->fetchAlgorithmsOfUser($user->uid, $ownAccount, NUMBER_OF_MY_ALGORITHMS);
    ?>
    <!-- HEADER -->
    <div class="page-header">
        <h1>
            <?= $l10n['user'] ?>
            <small><?= $user->username ?></small>
        </h1>
    </div>
    <!-- HEADER END -->

    <!-- CONTENT -->
    <div id="success" class="alert alert-success alert-dismissible" role="alert" style="display:none">
        <button type="button" class="close" aria-label="<?= $l10n['close'] ?>"><span aria-hidden="true">&times;</span></button>
        <strong><?= $l10n['success'] ?></strong>

        <div id="successText"></div>
    </div>
    <div id="alert" class="alert alert-danger alert-dismissible" role="alert" style="display:none">
        <button type="button" class="close" aria-label="<?= $l10n['close'] ?>"><span aria-hidden="true">&times;</span></button>
        <strong><?= $l10n['error'] ?></strong>

        <div id="alertText"></div>
    </div>
    <div class="row">
        <!-- LEFT COLUMN -->
        <div class="col-md-6">
            <div class="well">
                <h3><?= $l10n['algorithms'] ?></h3>
                <?php if ($algorithms): ?>
                    <table class="table table-sortable algorithms">
                        <tbody>
                        <?php foreach ($algorithms as $algorithm): $link = url(['action' => 'view', 'aid' => $algorithm['aid']]) ?>
                            <tr>
                                <td>
                                    <?php if ($algorithm['age'] <= MAX_MINUTES_FOR_LABEL): ?>
                                        <span class="label label-default"><?= $l10n['label_new'] ?></span>
                                    <?php endif ?>
                                    <?php if (is_null($algorithm['date_publish'])): ?>
                                        <span class="label label-info"><?= $l10n['private'] ?></span>
                                    <?php endif ?>
                                    <span class="name">
                                        <a href="<?= $link ?>">
                                            <?= $algorithm['name'] ? $algorithm['name'] : $l10n['untitled_algorithm'] ?>
                                        </a>
                                    </span>
                                    <span class="properties">
                                        (<?= sprintf($l10n['created_at'], getTimeFrame($algorithm['age'])) ?>)
                                    </span>
                                    <?php if (!empty($algorithm['description'])): ?>
                                        <span class="description">
                                            <?= skipDescription($algorithm['description']) ?>
                                        </span>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                        <?php
                            $colCount = 1;
                            // require(BASEDIR . 'partials/partials/table_foot.phtml');
                        ?>
                    </table>
                <?php else: ?>
                    <div><?= $l10n['no_algorithms'] ?></div>
                <?php endif ?>
            </div>
        </div>
        <!-- LEFT COLUMN END -->

        <!-- RIGHT COLUMN -->
        <div class="col-md-6">
            <div class="well">
                <?php
                $countAll = $__model->countAlgorithmsOfUser($user->uid, true);
                $countPublic = $__model->countAlgorithmsOfUser($user->uid);
                $countForked = $__model->countAlgorithmsOfUser($user->uid, true, true);
                ?>
                <h3><?= $user->username ?></h3>
                <p><?= sprintf($l10n['member_since'], date_create($user->date_registration)->format('F j, Y')) ?></p>
                <hr/>
                Total number of algorithms: <?= $countAll ?>
                <ul>
                    <li><i class="fa fa-lock"></i> Number of private algorithms: <?= $countAll - $countPublic ?></li>
                    <li><i class="fa fa-code-fork"></i> Number of copied algorithms: <?= $countForked ?></li>
                </ul>
            </div>
            <?php if ($ownAccount): ?>
                <div class="well">
                    <h3><?= $l10n['account_settings'] ?></h3>

                    <form id="usernameForm" class="form-horizontal" role="form" method="post"
                          action="<?= url(['action' => 'user', 'uid' => $__uid]) ?>">
                        <div id="username-group" class="form-group">
                            <input id="usernameMsg" name="successMsg" style="display: none;"/>
                            <label for="in-username" class="control-label col-sm-4"><?= $l10n['username'] ?></label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="in-username" name="username" value="<?= $user->username ?>"/>
                            </div>
                            <div class="col-sm-3">
                                <a id="usernameBtn" class="btn btn-primary"><?= $l10n['change'] ?></a>
                            </div>
                        </div>
                    </form>
                    <div class="form-horizontal" role="form">
                        <div id="email-group" class="form-group">
                            <label for="in-email" class="control-label col-sm-4"><?= $l10n['email_address'] ?></label>

                            <div class="col-sm-5">
                                <input type="email" class="form-control" id="in-email" name="email" value="<?= $user->email ?>"/>
                            </div>
                            <div class="col-sm-3">
                                <a id="emailBtn" class="btn btn-primary"><?= $l10n['change'] ?></a>
                            </div>
                        </div>
                    </div>
                    <form id="passwordForm" class="form-horizontal" role="form" method="post"
                          action="<?= url(['action' => 'user', 'uid' => $__uid]) ?>">
                        <div id="password1-group" class="form-group">
                            <input id="passwordMsg" name="successMsg" style="display: none;"/>
                            <label for="in-password1" class="control-label col-sm-4"><?= $l10n['password'] ?></label>

                            <div class="col-sm-5">
                                <input type="password" class="form-control" id="in-password1" name="password1" placeholder="<?= $l10n['password'] ?>">
                            </div>
                            <div class="col-sm-3">
                                <a id="passwordBtn" class="btn btn-primary"><?= $l10n['change'] ?></a>
                            </div>
                        </div>
                        <div id="password2-group" class="form-group">
                            <label for="in-password2" class="control-label col-sm-4"></label>

                            <div class="col-sm-5">
                                <input type="password" class="form-control" id="in-password2" name="password2" placeholder="<?= $l10n['password_again'] ?>">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="alert alert-danger">
                    <h3><?= $l10n['delete_user'] ?></h3>

                    <div class="settings-delete">
                        <p><?= $l10n['delete_user_message'] ?></p>
                        <ul>
                            <li><?= $l10n['not_able_to_contribute'] ?></li>
                            <li><?= $l10n['delete_all_algorithms'] ?></li>
                        </ul>

                        <form id="deleteForm" class="form-horizontal" role="form" method="post" name="delete"
                              action="<?= url(['action' => 'home']) ?>">
                            <div class="row">
                                <input id="deleteMsg" name="successMsg" style="display: none;"/>
                                <label for="deletePassword" class="control-label sr-only"><?= $l10n['password'] ?></label>

                                <div id="password-group" class="col-sm-8">
                                    <input type="password" class="form-control" id="delete-password" name="password" placeholder="<?= $l10n['password'] ?>">
                                </div>
                                <div class="col-sm-4">
                                    <button id="deleteBtn" type="button" class="btn btn-danger" name="delete" data-warning="<?= $l10n['delete_user_warning'] ?>">
                                        <?= $l10n['delete_user'] ?>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            <?php endif ?>
        </div>
        <!-- RIGHT COLUMN END -->
    </div>
    <!-- CONTENT END -->
<?php else: // no user specified ?>
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close">
            <span aria-hidden="true">&times;</span><span class="sr-only"><?= $l10n['close'] ?></span>
        </button>
        <strong><?= $l10n['error'] ?></strong><br/>
        <?= $l10n['error_no_such_user'] ?><br/>
        &rarr; <a href="javascript:history.back()"><?= $l10n['go_back'] ?></a>
    </div>
<?php endif ?>