<?php
if (!defined('BASEDIR')) die('You cannot call this script directly !');
if (!isset($_GET['aid'])) {
    header("Location:" . url(['action' => 'index']));
    die();
}
// get algorithm id
$aid = $_GET['aid'];

// get algorithm details from database
require_once BASEDIR . "includes/dataModel.php";
$_model = new DataModel();
$_algo = $_model->fetchAlgorithmByAID($aid);
$_model->close();

// extract variables
$name = stripslashes($_algo->name);
$description = stripslashes($_algo->description);
$long_description = stripslashes($_algo->long_description);
$vars = json_decode($_algo->variables);

// prepare tree
require_once BASEDIR . "includes/nodes.php";
$tree = new Tree(json_decode($_algo->tree));

// open section if it is specified
$section = array ('controls' => false, 'pseudo' => false, 'source' => false,
    'desc' => false, 'memory' => false, 'stats' => false);
$sectionNum = isset($_GET['section']) ? $_GET['section'] : SECTIONS_VIEW;
if ($sectionNum >= 32) { $section['stats'] = true; $sectionNum -= 32; }
if ($sectionNum >= 16) { $section['memory'] = true; $sectionNum -= 16; }
if ($sectionNum >= 8) { $section['desc'] = true; $sectionNum -= 8; }
if ($sectionNum >= 4) { $section['source'] = true; $sectionNum -= 4; }
if ($sectionNum >= 2) { $section['pseudo'] = true; $sectionNum -= 2; }
if ($sectionNum >= 1) { $section['controls'] = true; }
?>
<!-- HEADER -->
<div class="page-header">
    <?php if (isset($aid)): ?>
    <h1><?= $name ?> <small><?= $description ?></small></h1>
    <?php endif ?>
</div>

<!-- CONTENT -->
<div class="row">

<!-- LEFT COLUMN -->
<div class="col-md-6">

    <!-- ALGORITHM AREA -->
    <div class="panel-group" id="accordion-left">

        <!-- TAB - CONTROLS -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#controls">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['controls']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $l10n['controls'] ?>
                </h4>
            </div>
            <div id="controls" class=" panel-collapse collapse <?= $section['controls'] ? 'in' : 'closed' ?>">
                <div class="panel-body">

                    <!-- STEP CONTROLS -->
                    <div class="btn-group btn-group-justified">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default"
                                    title="Back to beginning" id="btn-reset"
                                    disabled="disabled">
                                <span class="glyphicon glyphicon-fast-backward"></span>
                            </button>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default"
                                    title="Step back" id="btn-stepback"
                                    disabled="disabled">
                                <span class="glyphicon glyphicon-step-backward"></span>
                            </button>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default" title="Play"
                                    id="btn-play" data-toggle="button">
                                <span class="glyphicon glyphicon-play" id="img-play"></span>
                            </button>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default"
                                    title="Step forward" id="btn-step">
                                <span class="glyphicon glyphicon-step-forward"></span>
                            </button>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default"
                                    title="Forward to end" id="btn-finish">
                                <span class="glyphicon glyphicon-fast-forward"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- TAB - PSEUDOCODE -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#pseudocode">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['pseudo']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $name ?>
                </h4>
            </div>
            <div id="pseudocode" class="panel-collapse collapse <?= $section['pseudo'] ? 'in' : 'closed' ?>">
                <div class="panel-body algorithm">
                    <ul><?php $tree->printHtml(['vars' => $vars]) ?></ul>
                </div>
            </div>
        </div>

        <!-- TAB - SOURCE CODE -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#sourcecode">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['source']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $l10n['source_code'] ?>
                </h4>
            </div>
            <div id="sourcecode" class=" panel-collapse collapse <?= $section['source'] ? 'in' : 'closed' ?>">
                <div class="panel-body">
                    <pre><?php $tree->printSource(['vars' => $vars]) ?></pre>
                </div>
            </div>
        </div>

        <!-- TAB - DESCRIPTION -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#description">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['desc']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $l10n['description'] ?>
                </h4>
            </div>
            <div id="description" class=" panel-collapse collapse <?= $section['desc'] ? 'in' : 'closed' ?>">
                <div class="panel-body">
                    <?= $long_description ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- LEFT COLUMN END -->

<!-- RIGHT COLUMN -->
<div class="col-md-6">
    <div class="panel-group" id="accordion-right">

        <!-- TAB - MEMORY -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#memory">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['memory']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $l10n['memory'] ?>
                </h4>
            </div>
            <div id="memory" class=" panel-collapse collapse <?= $section['memory'] ? 'in' : 'closed' ?>">
                <div class="panel-body">
                    <table class="table table-hover table-bordered">
                        <tr>
                            <th style="border-top: none;"><?= $l10n['variable'] ?></th>
                            <th style="border-top: none;"><?= $l10n['contents'] ?></th>
                        </tr>
                        <?php foreach($vars as $index => $var): ?>
                        <tr>
                            <td><code><?= $var->name ?></code></td>
                            <td>
                                <div class="btn-group">
                                    <?php if (substr($var->init, 0, 6) == "array-"): // deal with "array-{?,custom,random}" ?>
                                        <?php foreach (explode(',', $var->value) as $offset => $value): ?>
                                            <input type="button" class="btn btn-default" disabled="disabled"
                                                   value="<?= $value ?>" id="memory-<?= $var->name ?><?= $offset ?>" />
                                        <?php endforeach ?>
                                    <?php else: // deal with "elem-{?,value}" ?>
                                        <input type="button" class="btn btn-default" disabled="disabled"
                                               value="<?= $var->value ?>" id="memory-<?= $var->name ?>" />
                                    <?php endif ?>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
        </div>

        <!-- TAB - STATISTICS -->
        <div class="panel panel-default">
            <div class="panel-heading" data-toggle="collapse" data-target="#statistics">
                <h4 class="panel-title">
                    <span class="glyphicon glyphicon-chevron-<?php if ($section['stats']): ?>down<?php else: ?>right<?php endif ?>"></span>
                    <?= $l10n['statistics'] ?>
                </h4>
            </div>
            <div id="statistics" class="panel-collapse collapse <?= $section['stats'] ? 'in' : 'closed' ?>">
                <div class="panel-body">
                    <table class="table table-hover table-bordered">
                        <tr>
                            <th><?= $l10n['metric'] ?></th>
                            <th><?= $l10n['count'] ?></th>
                        </tr>
                        <tr>
                            <td><?= $l10n['nowo'] ?></td>
                            <td>
                                <div class="btn-group">
                                    <input type="button" class="btn btn-default" disabled="disabled" value="0" id="stats-now" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><?= $l10n['noco'] ?></td>
                            <td>
                                <div class="btn-group">
                                    <input type="button" class="btn btn-default" disabled="disabled" value="0" id="stats-noc" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><?= $l10n['nooo'] ?></td>
                            <td>
                                <div class="btn-group">
                                    <input type="button" class="btn btn-default" disabled="disabled" value="0" id="stats-noo" />
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- RIGHT COLUMN END -->

</div>
<!-- CONTENT END -->

<!-- TODO: remove link after presentation -->
<ul class="pager">
    <li class="previous"><a href="../pres/#/overview">&larr; Back to presentation</a></li>
</ul>