<?php
$linkAlgorithm = url(['action' => 'view', 'aid' => $algorithm['aid']]);
$linkUser = url(['action' => 'user', 'uid' => $algorithm['uid']]);
?>
<tr>
    <td>
        <?php if (is_null($algorithm['date_publish'])): ?>
            <span class="label label-info"><?= $l10n['private'] ?></span>
        <?php endif ?>
        <span class="name">
            <a href="<?= $linkAlgorithm ?>">
                <?= $algorithm['name'] ? $algorithm['name'] : $l10n['untitled_algorithm'] ?>
            </a>
        </span>
        <span class="properties">
            (<?= sprintf($l10n['modified_note'], getTimeFrame($algorithm['modified']),
                '<a href="' . $linkUser . '">' . $algorithm['username']) . '</a>' ?>)
        </span>
        <?php if (!empty($algorithm['description'])): ?>
            <span class="description"><?= skipDescription($algorithm['description']) ?></span>
        <?php endif ?>
    </td>
</tr>