<?php
/**
 * Used by index.phtml
 * The surrounding file has to guarantee the existence of the following variables:
 * - $user: array containing user information
 * - $l10n: array used for translation
 */
?>
<tr>
    <td><a href="<?= url(['action' => 'user', 'uid' => $user['uid']]) ?>"><?= $user['username'] ?></a></td>
    <td><?= $user['count'] ?></td>
    <td><?= $user['date_registration'] ?></td>
</tr>