<?php
$link = url(['action' => 'view', 'aid' => $algorithm['aid']])
?>
<tr>
    <td>
        <?php if ($algorithm['age'] <= MAX_MINUTES_FOR_LABEL): ?>
            <span class="label label-default"><?= $l10n['label_new'] ?></span>
        <?php endif ?>
        <?php if (is_null($algorithm['date_publish'])): ?>
            <span class="label label-info"><?= $l10n['private'] ?></span>
        <?php endif ?>
        <span class="name">
            <a href="<?= $link ?>">
                <?= $algorithm['name'] ? $algorithm['name'] : $l10n['untitled_algorithm'] ?>
            </a>
        </span>
        <span class="properties">
            (<?= sprintf($l10n['created_at'], getTimeFrame($algorithm['age'])) ?>)
        </span>
        <?php if (!empty($algorithm['description'])): ?>
            <span class="description">
                <?= skipDescription($algorithm['description']) ?>
            </span>
        <?php endif ?>
    </td>
</tr>