<?php
/**
 * Used by index.phtml
 * The surrounding file has to guarantee the existence of the following variables:
 * - $algorithm: array containing algorithm information
 * - $l10n: array used for translation
 */
?>
<tr>
    <td>
        <a href="<?= url(['action' => 'view', 'aid' => $algorithm['aid']]) ?>">
            <?= $algorithm['name'] ? $algorithm['name'] : $l10n['untitled_algorithm'] ?>
        </a>
    </td>
    <td>
        <?php foreach (explode(', ', $algorithm['tags']) as $tag): ?>
            <a href="<?= url(['action' => 'index', 'tab' => 'tags', 'tag' => $tag]) ?>">
                <span class="badge"><?= $tag ?></span>
            </a>
        <?php endforeach ?>
    </td>
    <td>
        <a href="<?= url(['action' => 'user', 'uid' => $algorithm['uid']]) ?>">
            <?= $algorithm['owner'] ?>
        </a>
    </td>
    <td><?= $algorithm['date_creation'] ?></td>
    <td><?= $algorithm['date_lastedit'] ?></td>
    <td><?= ($size = $algorithm['size'] ? $size : 0) > 1024 ? $size / 1024 . ' KiB' : $size . ' B' ?></td>
</tr>