// Generated by CoffeeScript 1.10.0
(function() {
  var Api;

  Api = (function() {
    function Api() {}

    Api.deleteUser = function(uid, callback) {
      return $.ajax("api/user.php", {
        type: 'POST',
        data: {
          remove: uid,
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback(data['status']);
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.eraseUser = function(uid, callback) {
      return $.ajax("api/user.php", {
        type: 'POST',
        data: {
          erase: uid,
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback();
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.unDeleteUser = function(uid, callback) {
      return $.ajax("api/user.php", {
        type: 'POST',
        data: {
          resurrect: uid,
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback(data['status']);
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.toggleAdmin = function(uid, callback) {
      return $.ajax("api/user.php", {
        type: 'POST',
        data: {
          admin: uid,
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback();
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.deleteAlgorithm = function(aid, callback) {
      return $.ajax("api/algorithm.php?area=admin", {
        type: 'POST',
        data: {
          aid: aid,
          action: 'remove',
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback(data['status']);
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.eraseAlgorithm = function(aid, callback) {
      return $.ajax("api/algorithm.php?area=admin", {
        type: 'POST',
        data: {
          aid: aid,
          action: 'erase',
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback();
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api.unDeleteAlgorithm = function(aid, callback) {
      return $.ajax("api/algorithm.php?area=admin", {
        type: 'POST',
        data: {
          aid: aid,
          action: 'resurrect',
          lang: window.current.lang
        },
        dataType: 'json',
        success: (function(_this) {
          return function(data, textStatus, jqXHR) {
            var msg, ref;
            msg = (ref = data['error']) != null ? ref : "";
            if (msg !== "") {
              return _this._printError(msg);
            } else {
              _this._printSuccess(data['success']);
              return callback(data['status']);
            }
          };
        })(this),
        error: (function(_this) {
          return function(jqXHR, textStatus, errorThrown) {
            return _this._printError("AJAX Error: " + textStatus);
          };
        })(this)
      });
    };

    Api._printSuccess = function(msg) {
      $('#successText').html(msg);
      $('#success').show('slow');
      return $('#alert').hide('slow');
    };

    Api._printError = function(msg) {
      $('#alertText').html(msg);
      $('#alert').show('slow');
      return $('#success').hide('slow');
    };

    return Api;

  })();

  $(function() {
    $('.filter').click(function() {
      var col, target, txt;
      col = $(this).data('column');
      txt = $(this).data('filter');
      target = $(this).data('target');
      $(target).find('.tablesorter-filter').val('').eq(col).val(txt);
      $(target).trigger('search', false);
      return false;
    });
    $('.delete-user').click(function() {
      var row, uid;
      row = $(this).closest('tr');
      uid = row.data('uid');
      return Api.deleteUser(uid, function(status) {
        row.find('.status').text(status);
        return row.addClass('deleted');
      });
    });
    $('.erase-user').click(function() {
      var row, uid;
      row = $(this).closest('tr');
      uid = row.data('uid');
      if (confirm($(this).data('warning'))) {
        return Api.eraseUser(uid, function() {
          return row.remove();
        });
      }
    });
    $('.un-delete-user').click(function() {
      var row, uid;
      row = $(this).closest('tr');
      uid = row.data('uid');
      return Api.unDeleteUser(uid, function(status) {
        row.find('.status').text(status);
        return row.removeClass('deleted');
      });
    });
    $('.adminify-user').click(function() {
      var row, uid, username;
      row = $(this).closest('tr');
      uid = row.data('uid');
      username = row.find('.username');
      return Api.toggleAdmin(uid, function() {
        return username.toggleClass('admin');
      });
    });
    $('.delete-algorithm').click(function() {
      var aid, row;
      row = $(this).closest('tr');
      aid = row.data('aid');
      return Api.deleteAlgorithm(aid, function(status) {
        row.find('.status').text(status);
        return row.addClass('deleted');
      });
    });
    $('.erase-algorithm').click(function() {
      var aid, row;
      row = $(this).closest('tr');
      aid = row.data('aid');
      if (confirm($(this).data('warning'))) {
        return Api.eraseAlgorithm(aid, function() {
          return row.remove();
        });
      }
    });
    return $('.un-delete-algorithm').click(function() {
      var aid, row;
      row = $(this).closest('tr');
      aid = row.data('aid');
      return Api.unDeleteAlgorithm(aid, function(status) {
        row.removeClass('deleted');
        return row.find('.status').text(status);
      });
    });
  });

}).call(this);
