// Generated by CoffeeScript 1.7.1

/*
Unbiased shuffle algorithm for arrays
https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

  @param array the unshuffled array
  @returns the shuffled array
 */

(function() {
  var shuffle;

  shuffle = function(array) {
    var currentIndex, randomIndex, _ref;
    currentIndex = array.length;
    while (currentIndex !== 0) {
      randomIndex = Math.floor(Math.random() * currentIndex--);
      _ref = [array[randomIndex], array[currentIndex]], array[currentIndex] = _ref[0], array[randomIndex] = _ref[1];
    }
    return array;
  };

}).call(this);

//# sourceMappingURL=custom.map
