// Generated by CoffeeScript 1.10.0
(function() {
  var register;

  register = function() {
    return $.ajax("api/register.php", {
      type: 'POST',
      data: {
        username: $('#in-username').val(),
        email: $('#in-email').val(),
        password1: $('#in-password1').val(),
        password2: $('#in-password2').val(),
        lang: window.current.lang
      },
      dataType: 'json',
      success: function(data) {
        var i, len, msg, ref, ref1, token;
        msg = (ref = data['error']) != null ? ref : "";
        ref1 = ['username', 'email', 'password1', 'password2'];
        for (i = 0, len = ref1.length; i < len; i++) {
          token = ref1[i];
          if (data['error-' + token] != null) {
            msg += data['error-' + token];
            $('#' + token + '-group').addClass('has-error');
          } else {
            $('#' + token + '-group').removeClass('has-error');
          }
        }
        if (msg !== "") {
          $('#alertText').html(msg);
          return $('#alert').show('slow');
        } else {
          return $('#registerForm').submit();
        }
      },
      error: function(jqXHR, textStatus) {
        $('#alertText').html("AJAX Error: " + textStatus);
        return $('#alert').show('slow');
      }
    });
  };

  $(function() {
    $('#registerBtn').click(function() {
      return register();
    });
    return $('#registerForm input').keypress(function(event) {
      if (event.which === 13) {
        return register();
      }
    });
  });

}).call(this);
