// Generated by CoffeeScript 1.10.0
(function() {
  var change, changeEmail, changePassword, deleteMe, renameMe;

  change = function(params, callback) {
    return $.ajax("api/user.php", {
      type: 'POST',
      data: params,
      dataType: 'json',
      success: function(data, textStatus, jqXHR) {
        var i, len, msg, ref, ref1, token;
        msg = (ref = data['error']) != null ? ref : "";
        ref1 = ['username', 'email', 'password1', 'password2', 'password'];
        for (i = 0, len = ref1.length; i < len; i++) {
          token = ref1[i];
          if (data['error-' + token] != null) {
            msg += data['error-' + token];
            $('#' + token + '-group').addClass('has-error');
          } else {
            $('#' + token + '-group').removeClass('has-error');
          }
        }
        if (msg !== "") {
          $('#alertText').html(msg);
          $('#alert').show('slow');
          return $('#success').hide('slow');
        } else {
          $('#successText').html(data['success']);
          $('#success').show('slow');
          $('#alert').hide('slow');
          return callback(data['success']);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        $('#alertText').html("AJAX Error: " + textStatus);
        return $('#alert').show('slow');
      }
    });
  };

  renameMe = function() {
    var username;
    username = $('#in-username').val();
    change({
      username: username,
      lang: window.current.lang
    }, function(msg) {
      $('#usernameMsg').val(msg);
      return $('#usernameForm').submit();
    });
    return username;
  };

  deleteMe = function() {
    var password;
    password = $('#delete-password').val();
    if (confirm($('#deleteBtn').data('warning'))) {
      return change({
        password: password
      }, function(msg) {
        $('#deleteMsg').val(msg);
        return $('#deleteForm').submit();
      });
    }
  };

  changeEmail = function() {
    var email;
    email = $('#in-email').val();
    change({
      email: email,
      lang: window.current.lang
    }, function() {});
    return email;
  };

  changePassword = function() {
    var password1, password2;
    password1 = $('#in-password1').val();
    password2 = $('#in-password2').val();
    return change({
      password1: password1,
      password2: password2,
      lang: window.current.lang
    }, function(msg) {
      $('#passwordMsg').val(msg);
      return $('#passwordForm').submit();
    });
  };

  $(function() {
    $('#usernameBtn').click(function() {
      return renameMe();
    });
    $('#emailBtn').click(function() {
      return changeEmail();
    });
    $('#passwordBtn').click(function() {
      return changePassword();
    });
    $('#deleteBtn').click(function() {
      return deleteMe();
    });
    $('#in-username').keypress(function(event) {
      if (event.which === 13) {
        return renameMe();
      }
    });
    $('#in-email').keypress(function(event) {
      if (event.which === 13) {
        return changeEmail();
      }
    });
    $('#in-password1, #in-password2').keypress(function(event) {
      if (event.which === 13) {
        return changePassword();
      }
    });
    return $('#delete-password').keypress(function(event) {
      if (event.which === 13) {
        return deleteMe();
      }
    });
  });

}).call(this);
