<?php if (!defined('BASEDIR')) die('You cannot call this script directly !') ?>
<?php if ($__aid): ?>
    <?php if ($__uid): ?>
        <!-- NAVIGATION MENU FOR ALGORITHMS -->
        <ul class="nav nav-tabs">
            <li role="presentation"<?php if (ACTION == 'view'): ?> class="active"<?php endif ?>>
                <a href="<?= url(['action' => 'view', 'aid' => $__aid]) ?>"><?= $l10n['view'] ?></a>
            </li>
            <?php if ($__owner): ?>
                <li role="presentation"<?php if (ACTION == 'edit'): ?> class="active"<?php endif ?>>
                    <a href="<?= url(['action' => 'edit', 'aid' => $__aid]) ?>"><?= $l10n['edit'] ?></a>
                </li>
                <li role="presentation"<?php if (ACTION == 'settings'): ?> class="active"<?php endif ?>>
                    <a href="<?= url(['action' => 'settings', 'aid' => $__aid]) ?>"><?= $l10n['settings'] ?></a>
                </li>
            <?php else: ?>
                <li role="presentation" class="disabled">
                    <a href="javascript:void(0)"><?= $l10n['edit'] ?></a>
                </li>
                <li role="presentation" class="disabled">
                    <a href="javascript:void(0)"><?= $l10n['settings'] ?></a>
                </li>
            <?php endif ?>
        </ul>
    <?php endif ?>
    <script type="text/javascript">
        window.defaults.aid = <?= $__aid ?>;
    </script>
<?php endif ?>